# Generated by Django 3.2.5 on 2021-07-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210708_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='publised_on',
            new_name='published_on',
        ),
    ]
