# Generated by Django 3.2.5 on 2021-07-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_publised_on_products_published_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='avg_ratings',
        ),
        migrations.RemoveField(
            model_name='products',
            name='rating_count',
        ),
    ]
