# Generated by Django 3.2.5 on 2021-08-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210714_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='published_on',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
